/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : OrderId,
  'total' : bigint,
  'owner' : Principal,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'color' : [] | [string],
  'size' : [] | [string],
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'imageUrl' : string,
  'category' : string,
  'colors' : Array<string>,
  'price' : bigint,
}
export type ProductId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, bigint, string, string, Array<string>, Array<string>],
    ProductId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[Array<OrderItem>, bigint], OrderId>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<
    [
      ProductId,
      string,
      string,
      bigint,
      string,
      string,
      Array<string>,
      Array<string>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];